{% set name = "rasam" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JoelJaeschke/rasam/archive/v{{ version }}.tar.gz
  sha256: 68e0b45ee2f78ac3a9397f35f1259f1fe25860470aed68906589d3430db59a38

build:
  number: 1

requirements:
  build:
    - make
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - libgdal >=3.7.0

test:
  commands:
    - rasam -h

about:
  home: https://github.com/JoelJaeschke/rasam
  summary: 'Sample raster files using GDAL'
  description: |
    This tool samples raster files (like GeoTIF, ASCII etc..) given a
    vector file of points.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/JoelJaeschke/rasam
  dev_url: https://github.com/JoelJaeschke/rasam

extra:
  recipe-maintainers:
    - JoelJaeschke
